[tool.poetry]
name = "ltt_ff_frontend"
version = "0.8.0"
description = ""
authors = ["Michael Hsieh <michael.hsieh@lasertectaiwan.com>"]
readme = "README.md"
repository = "http://gitlab.lttsoftware.com/swrd/mle/ltt-ff-frontend"

[tool.poetry.dependencies]
python = "3.11.10"
loguru = "^0.7.3"
python-dotenv = "^1.0.1"
pyyaml = "^6.0.2"
requests = "^2.32.3"
streamlit = "^1.44.1"
pandas = "^2.2.3"
numpy = "^2.2.4"
scikit-learn = "^1.6.1"
pydantic = "^2.11.3"

[tool.poetry.group.viz.dependencies]
pillow = "^11.2.1"
matplotlib = "^3.10.1"
plotly = "^6.0.1"
seaborn = "^0.13.2"
matplotlib-venn = "1.1.2"

[tool.poetry.group.test.dependencies]
pre-commit = "^4.2.0"
# Linting
ruff = "^0.11.5"
pylint = "^3.3.6"
# Linting - Type Check
mypy = "^1.15.0"
pandas-stubs = "^2.2.3.250308"
types-pyyaml = "^6.0.12.20250402"
types-requests = "^2.32.0.20250328"
# Testing
pytest = "^8.3.5"
coverage = "^7.8.0"
pytest-cov = "^6.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

    [tool.ruff.lint]
    select = [
        "F",  # pyflakes
        "E", "W",  # pycodestyle
        "PLC", "PLE", "PLW",  # pylint
        "I",  # isort
        "B",  # flake8-bugbear
        "C4",
        "UP",
        "PT",

        "PIE",
        "A",
        "TID",
        "ICN",
        "DTZ",
        "RSE",
        "ARG",

        "LOG",
        "G",
        "FLY",
        "T20",
        "T10",
        "S102",

        "PERF",
        "FURB",
    ]

    [tool.ruff.lint.isort]
    lines-after-imports = 2

[tool.pylint]
    extension-pkg-allow-list = [
        "cv2",
    ]
    generated-members = [
        "cv2",
    ]

    [tool.pylint.message_control]
    disable = [
        "fixme",
        "too-few-public-methods",
        "no-else-return",
        "missing-module-docstring",
        "missing-class-docstring",
        "missing-function-docstring",
    ]

    [tool.pylint.format]
    max-line-length = 120
    min-similarity-lines = 10

    [tool.pylint.design]
    max-args = 10
    max-locals = 30

    [tool.pylint.reports]
    score = false
    output-format = "colorized"

[tool.mypy]
pretty = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
