from ltt_ff_frontend.constant import HIDE_CREDENTIAL
DEFAULT_DATA_YAML = "/mnt/dbpc/FalseFilterDataSet/WeeklyYaml/WXXX_data_XXX.yaml"
DEFAULT_OUTPUT_PATH = "/mnt/output/mle_regression_test/" if not HIDE_CREDENTIAL else "/mnt/dbpc/xxx/"
UPDATE_TEXT_EXAMPLE = (
                    "WEEK2\n"
                    "LG1\n"
                    "[LG1][SITE1] *new* MMDD-XXXXXX  (TH: 0, THC: 0.2) MMDD-YYYYYY  (TH: 0, THC: 0.5)\n"
                    "[LG1][SITE2] MMDD-XXXXXX (TH: 0.14) MMDD-XXXXXX  (TH: 0.3)\n"
                    )
DATA_HELP_TEXT = f"**Example:**\n```yaml\n{DEFAULT_DATA_YAML}\n```"
RECIPE_HELP_TEXT = (
    "**Regression Recipe Format**\n\n"
    "The recipe config used for regression testing is different from the one used for regular inference. "
    "It should follow the format:\n\n"
    "`LayerGroup → Week → Site → Recipes`\n\n"
    "**Example:**\n"
    "```yaml\n"
    "LG1:\n"
    "  'WEEK1':\n"
    "    SITE1:\n"
    "      recipes:\n"
    "      - model_id: XXXXXX\n"
    "        threshold: 0.0\n"
    "        threshold_c: 0.5\n"
    "  'WEEK2':\n"
    "    SITE1:\n"
    "      recipes:\n"
    "      - model_id: YYYYYY\n"
    "        threshold: 0.0\n"
    "        threshold_c: 0.2\n"
    "```"
)

RECIPE_UPLOAD_HELP_TEXT = (
    "**Uploading Regression Recipe Updates**\n\n"
    "You can upload a file to update regression recipes in **two formats**: **TXT** or **YAML**.\n\n"
    "### 🔹 TXT Format\n"
    "Used for batch updates across multiple recipes. The file should begin with the target **Week**, "
    "followed by each **LayerGroup**, and then list the new recipe information line by line.\n\n"
    "**Example:**\n"
    "```\n"
    "WEEK2\n"
    "LG1\n"
    "[LG1][SITE1] *new* MMDD-XXXXXX (TH: 0, THC: 0.2) MMDD-YYYYYY (TH: 0, THC: 0.5)\n"
    "[LG1][SITE2] MMDD-WWWWWW  (TH: 0.14) MMDD-ZZZZZZ (TH: 0.3)\n"
    "```\n\n"
    "### 🔹 YAML Format\n"
    "Used for updating a **single recipe**. The filename must follow the format:\n"
    "`Week_LayerGroup_Site.yaml` (e.g., `WWEEK2_LG1_SITE1.yaml`)\n\n"
    "The content should follow the standard recipe YAML structure:\n"
    "```yaml\n"
    "recipes:\n"
    "- model_name: base/LTT_SW#XXX.pth\n"
    "  threshold: 0.02\n"
    "- model_name: base/LTT_SW#YYY.pth\n"
    "  threshold: 0.1573\n"
    "```\n\n"
    "Make sure the format is correct to ensure successful updates."
)
