DEFAULT_DATA_YAML = "/mnt/dbpc/FalseFilterDataSet/WeeklyYaml/WXXX_data_XXX.yaml"
DEFAULT_OUTPUT_PATH = "/mnt/output/mle_regression_test/"
UPDATE_TEXT_EXAMPLE = """529
                    ODPO
                    [OD][F20] *new* 0710-34764f49 (TH: 0, THC: 0.2) 0710-cd2a4c02 (TH: 0, THC: 0.5)
                    [OD][F12] 0424-a4058515 (TH: 0.14) 0522-009dc97e (TH: 0.3)
                    """
DATA_HELP_TEXT = f"**Example:**\n```yaml\n{DEFAULT_DATA_YAML}\n```"
RECIPE_HELP_TEXT = (
    "**Regression Recipe Format**\n\n"
    "The recipe config used for regression testing is different from the one used for regular inference. "
    "It should follow the format:\n\n"
    "`LayerGroup → Week → Site → Recipes`\n\n"
    "**Example:**\n"
    "```yaml\n"
    "OD:\n"
    "  '528':\n"
    "    F20:\n"
    "      recipes:\n"
    "      - model_id: e02efe32\n"
    "        threshold: 0.0\n"
    "        threshold_c: 0.5\n"
    "  '529':\n"
    "    F20:\n"
    "      recipes:\n"
    "      - model_id: 34764f49\n"
    "        threshold: 0.0\n"
    "        threshold_c: 0.2\n"
    "```"
)

RECIPE_UPLOAD_HELP_TEXT = (
    "**Uploading Regression Recipe Updates**\n\n"
    "You can upload a file to update regression recipes in **two formats**: **TXT** or **YAML**.\n\n"
    "### 🔹 TXT Format\n"
    "Used for batch updates across multiple recipes. The file should begin with the target **Week**, "
    "followed by each **LayerGroup**, and then list the new recipe information line by line.\n\n"
    "**Example:**\n"
    "```\n"
    "529\n"
    "ODPO\n"
    "[OD][F20] *new* 0710-34764f49 (TH: 0, THC: 0.2) 0710-cd2a4c02 (TH: 0, THC: 0.5)\n"
    "[OD][F12] 0424-a4058515 (TH: 0.14) 0522-009dc97e (TH: 0.3)\n"
    "```\n\n"
    "### 🔹 YAML Format\n"
    "Used for updating a **single recipe**. The filename must follow the format:\n"
    "`Week_LayerGroup_Site.yaml` (e.g., `W529_ODPO_F20.yaml`)\n\n"
    "The content should follow the standard recipe YAML structure:\n"
    "```yaml\n"
    "recipes:\n"
    "- model_name: base/LTT_SW#XXX.pth\n"
    "  threshold: 0.02\n"
    "- model_name: base/LTT_SW#YYY.pth\n"
    "  threshold: 0.1573\n"
    "```\n\n"
    "Make sure the format is correct to ensure successful updates."
)
